name: prophet_clean
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.2
  - pip:
      - prophet==1.1.5
      - customtkinter==5.2.2
      - tkinterdnd2==0.3.0
      - plotly